ilbright/urls.py
from django.urls import path

from . import views

app_name = 'ilbright'
urlpatterns = [
    path('', views.index, name='index'),
    path('send/', views.send, name='send'),
]

ilcam/urls.py
from django.urls import path

from . import views

app_name = 'ilcam'
urlpatterns = [
    path('', views.index, name='index'),
    path('send/', views.send, name='send'),
]

ildis/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'ildis'

urlpatterns = [
    path('', include('snake.urls')),
    path('suggestions/', include('suggestions.urls')),
    path('admin/', views.index_admin, name='index_admin'),
    path('admin/brightness/', include('ilbright.urls')),
    path('admin/text/', include('iltext.urls')),
    path('admin/camera/', include('ilcam.urls')),
    path('admin/specials/', include('specials.urls')),
    path('admin/admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

ilbright/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.apps import apps
from django.contrib.auth.decorators import login_required

import logging

logger = logging.getLogger(__name__)

@login_required
def index(request):
    return render(request, 'ilbright/index.html', {})

@login_required
def send(request):
    ilcon = apps.get_app_config('ilcon').ilcon

    try:
        brightness = request.POST['brightness']
        bright_int = int(brightness)
        if bright_int >= 0 and bright_int < 255:
            ilcon.set_brightness(bright_int)
    except:
        pass

    return HttpResponseRedirect(reverse('ilbright:index'))

ilbright/templates/ilbright/index.html
{% extends "base_admin.html" %}

{% block head %}
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'ilbright/style.css' %}">

<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'ilbright/ilbright.js' %}"></script>

{% endblock %}

{% block content %}

{# Display a form #}
<form action="{% url 'ilbright:send' %}" method="post" class="form">
  {% csrf_token %}
  <input id="range" type="range" min="0" max="255"
         name="brightness" class="form-range" autofocus
         oninput="showBrightness()"
         onchange="changeBrightness()">
  <label>brightness: <span id="cur-brightness">0</span></label>
  <br>
  <button type="submit" class="btn btn-primary">Send</button>
</form>

{% endblock %}