ilcam/urls.py
from django.urls import path

from . import views

app_name = 'ilcam'
urlpatterns = [
    path('', views.index, name='index'),
    path('send/', views.send, name='send'),
]

ildis/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'ildis'

urlpatterns = [
    path('', include('snake.urls')),
    path('suggestions/', include('suggestions.urls')),
    path('admin/', views.index_admin, name='index_admin'),
    path('admin/brightness/', include('ilbright.urls')),
    path('admin/text/', include('iltext.urls')),
    path('admin/camera/', include('ilcam.urls')),
    path('admin/specials/', include('specials.urls')),
    path('admin/admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

snake/urls.py
from django.urls import path

from . import views

app_name = 'snake'
urlpatterns = [
    path('', views.index, name='index'),
    path('scores', views.get_high_scores, name='scores')
]

snake/models.py
from django.db import models

from datetime import datetime
from datetime import timedelta

def validate_condition(con):
    if not con:
        raise Exception()

class SnakeScore(models.Model):
    score = models.PositiveIntegerField()
    date = models.DateTimeField(auto_now=True)
    user_name = models.CharField(max_length=3, blank=True)
    user_hallway = models.PositiveSmallIntegerField(blank=True, null=True)

    def add_score(score, user_name, user_hallway):
        score = SnakeScore.validate_score(score)
        user_name = SnakeScore.validate_user_name(user_name)
        user_hallway = SnakeScore.validate_user_hallway(user_hallway)

        print("saving score")
        print(score)
        print(user_name)
        print(user_hallway)

        score = SnakeScore(score = score, user_name = user_name,
                           user_hallway = user_hallway)
        score.save()

        return score.pk

    def validate_score(score):
        validate_condition(isinstance(score, int))

        return max(score, 0)

    def validate_user_name(un):
        if un == '':
            return ''

        validate_condition(isinstance(un, str))
        validate_condition(len(un) <= 3)
        validate_condition(un.isalnum())
        
        return un.ljust(3, '_').upper()

    def validate_user_hallway(uh):
        if uh == '':
            return None

        uh = int(uh)
        validate_condition(isinstance(uh, int))
        validate_condition(uh <= 150 and uh >= 1)
            
        return uh

    def ranking(self):
        rs = Highscore.objects.filter(score__gt=self.score)
        return rs.aggregate(ranking=Count('score'))['ranking'] + 1

    def get_high_scores(n, time_limit=None):
        objs = SnakeScore.objects;
        if time_limit:
            objs = objs.filter(date__gte=time_limit)
        return SnakeScore.objects.order_by('-score')[:n]

    def get_daily_high_scores(n):
        return SnakeScore.get_high_scores(n, datetime.now() - timedelta(days=1))

    def get_weekly_high_scores(n):
        return SnakeScore.get_high_scores(n, datetime.now() - timedelta(weeks=1))

    def get_monthly_high_scores(n):
        return SnakeScore.get_high_scores(n, datetime.now() - timedelta(weeks=4))

    def get_yearly_high_scores(n):
        return SnakeScore.get_high_scores(n, datetime.now() - timedelta(days=365))

snake/views.py
from django.shortcuts import render
from django.apps import apps
from django.http import JsonResponse
from django.core import serializers

from .models import SnakeScore


def index(request):
    return render(request, 'snake/index.html', {})

def get_high_scores(request):
    n = 10

    all_scores = SnakeScore.get_high_scores(n)
    yearly_scores = SnakeScore.get_yearly_high_scores(n)
    monthly_scores = SnakeScore.get_monthly_high_scores(n)
    weekly_scores = SnakeScore.get_weekly_high_scores(n)
    daily_scores = SnakeScore.get_daily_high_scores(n)

    def ser(data):
        return list(data.values())

    scores = {
        "all_time": ser(all_scores),
        "yearly": ser(yearly_scores),
        "monthly": ser(monthly_scores),
        "weekly": ser(weekly_scores),
        "daily": ser(daily_scores),
    }


    return JsonResponse(scores)

snake/templates/snake/index.html
{% extends "base_public.html" %}

{% block head %}
{% load static %}

<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% endblock %}

{% block nav %}
<style>
  #nav-brand {
      color: #dc3545;
      font-weight: bold;
  }
  #snake-brand {
      color: #198754;
      font-style: italic;
  }
  #slogan {
      font-style: italic;
      color: #dc3545;
  }
</style>

<a class="navbar-brand" id="nav-brand" href="{% url 'snake:index' %}">
  Leddie<span id="snake-brand">Snake</span>
</a>

<span id="slogan">
  Play Snake at Hoogeveldt!
</span>
{% endblock %}

{% block content %}

<script>
  let socket;
  let protocol = window.location.protocol === "https:" ? "wss://" : "ws://";
  let prefix = protocol + window.location.host + "/ws/snake/";
  let touchStartX = 0, touchStartY = 0;
  let mirror = false;
  document.body.onload = setup;

  function setup() {
    $("#start-form").submit(startGame);
  }

  function setupGame(name, hall) {
    connect(name, hall);


    document.addEventListener("keydown", function (e) {
      keyDownHandler(e);
    }, false);
    document.addEventListener("touchstart", function (e) {
      touchStart(e.changedTouches[0]);
    }, false);
    document.addEventListener("touchend", function (e) {
      touchEnd(e.changedTouches[0]);
    }, false);
  }

  function startGame(e) {
    e.preventDefault();
    $("#start-screen").hide()
    $("#playing").show()

    let formData = new FormData(document.querySelector('#start-form'))
    let name = formData.get("name");
    let hall = formData.get("hall");

    if (!name) name = "";
    if (!hall) hall = "";

    console.log(name);
    console.log(hall);

    setupGame(name, hall);
  }

  function receiveMessage(messageObject) {
    msg = JSON.parse(messageObject.data);

    if (msg.msg === "score") {
      updateScore(msg.score);
    } else if (msg.msg === "game_over") {
      gameOver(msg.score_key);
    } else if (msg.msg === "color") {
      updateColor(msg.color, msg.color_name);
    }
  }

  function updateScore(score) {
    let scoreSpan = document.getElementById("score");

    scoreSpan.innerText = score;
  }

  function gameOver(score_key) {
    $("#playing").hide()
    $("#game-over").show()
    let scoreSpan = document.getElementById("final-score");
    scoreSpan.innerText = $("#score").text();

    updateColor([255, 255, 255], "unknown");

    $.getJSON("{% url 'snake:scores'%}", function (data) {
      let all_time = data["all_time"];
      let all_table = $("#all-time tbody");
      all_time.forEach(function (score, i) {
        add_score(i+1, all_table, score, score_key);
      });
    });
  }

  function add_score(rank, table, score, key) {
    let tr = $("<tr>");
    tr.append($("<td>").text(rank).attr("scope", "row"));
    tr.append($("<td>").text(score.user_name));
    tr.append($("<td>").text(score.user_hallway));
    tr.append($("<td>").text(score.score));

    if (score.id === key) {
      tr.addClass("your-score");
    }

    table.append(tr);
  }

  function updateColor(color, colorName) {
    console.log(color);

    $("#playing").css("background-color", "rgb(" + color[0] + ","
                  + color[1] + "," + color[2] + ")");

    $("#playing #color-name").css("background-color", "rgb(" +
                                  color[0] * 0.8 + ","
                                  + color[1] * 0.8 + "," + color[2] *
                                  0.8 + ")");

    $("#playing #color-name").text(colorName);
  }

  function touchStart(e) {
    touchStartX = e.clientX;
    touchStartY = e.clientY;
  }

  function touchEnd(e) {
    let endX = e.clientX;                                    
    let endY= e.clientY;

    let diffX = touchStartX - endX;
    let diffY = touchStartY - endY;

    if (Math.abs(diffX) > Math.abs(diffY)) {
      if (diffX > 0) {
        if (mirror) {
          send("e")
        } else {
          send("w");
        }
      } else {
        if (mirror) {
          send("w");
        } else {
          send("e");
        }
      }
    } else {
      if (diffY > 0) {
        send("n");
      } else {
        send("s");
      }
    }
  }

  function keyDownHandler(e) {
    if (e.key == "Right" || e.key == "ArrowRight" || e.key == "d") {
      if (mirror) {
        send("w")
      } else {
        send("e");
      }
    } else if (e.key == "Left" || e.key == "ArrowLeft" || e.key == "a") {
      if (mirror) {
        send("e")
      } else {
        send("w");
      }
    } else if (e.key == "Up" || e.key == "ArrowUp" || e.key == "w") {
      send("n")
    } else if (e.key == "Down" || e.key == "ArrowDown" || e.key == "s") {
      send("s")
    }
  }


  function connect(name, hall) {
    socket = new WebSocket(prefix + "connect/")
    socket.addEventListener('message', receiveMessage);

    socket.onopen = function () {
      socket.send
      (JSON.stringify({msg: "new",
                                  name: name,
                                  hall: hall}));
    };
  }

  function send(dir) {
    socket.send(JSON.stringify({ msg: "dir",
                                 direction: dir }))
  }
</script>

<style>
  .attention {
      color: black;
      background-color: #fff28f;
      padding: 0.2em;
      box-decoration-break: clone;
  }
  .your-score {
      background-color: #8dff64;
  }
  #high-scores table tr.your-score:hover {
      background-color: #8afa60;
  }
  #high-scores table tr:hover {
      background-color: #fbfbfb;
  }
  #high-scores {
      margin-top: 4em;
  }
  #final-score {
      text-weight: bold;
  }
  /* Fix chrome annoying swipe up to refresh behaviour */
  body {
      overscroll-behavior: contain;
  }
</style>

<div id="start-screen">
  <form id="start-form">
    <div class="mb-3 row">
      <div class="col">
        <label class="form-label">
          Name
        </label>
        <input class="form-control"
               type="text"
               maxlength="3"
               placeholder="ABC"
               name="name"
               >
      </div>
      <div class="col">
        <label class="form-label">
          Hall
        </label> 
        <input class="form-control"
               type="number"
               min="1"
               max="150"
               placeholder="99"
               name="hall"
               >
      </div>
    </div>

    <div class="mb-3 text-center">
      <button type="submit" class="btn btn-success fs-1">Play</button>
    </div>
  </form>

  <div id="instruction">
    <h1 class="text-center">How to play?</h1>

    <style>
      #instruction {
          margin-top: 4em
      }
      #instruction h1 {
          color: #dc3545;
          font-style: italic;
      }
      #instruction div.container-sm {
          max-width: 600px;
          padding: 2em;
      }
      #instruction p {
          font-size: 140%;
      }
      #instruction img {
          padding: 4%;
      }
      #instruction #intro {
          max-width: 750px;
          margin: auto;
          margin-top: 1.5em;
          margin-bottom: 1.5em;
          color: #444;
          font-size: 130%
      }
    </style>

    <p class="" id="intro">
      Compete against your fellow Hoogeveldt residents at a classic
      game of snake! You can play against up to two other players at
      the same time. Simply go
      to <a href="https://leddie.nl/">leddie.nl</a> and press
      play. Then, look at the window to see your snake move and get as
      many points as possible. Enter your name and hallway at the
      start to get your high score into the hall of fame!
    </p>
    

    <div class="container-sm">
      <div class="row justify-content-center align-self-center">
        <div class="col-4 justify-content-center align-self-center">
          <img class="img-fluid"
               src="/static/img/snake/explanation-1.png">
        </div>
        <p class="col-8 justify-content-center align-self-center">
          Don't look at your phone, look at
          the <span class="attention">LEDs screen on the
            window</span>!
        </p>
      </div>
    </div>

    <div class="container-sm">
      <div class="row justify-content-center align-self-center">
        <div class="col-4">
        <img class="img-fluid"
             src="/static/img/snake/explanation-2.png">
        </div>
        <p class="col-8 justify-content-center align-self-center">
          Change direction by swiping on <span class="attention">your
            phone</span>
        </p>
      </div>
    </div>

    <div class="container-sm">
      <div class="row justify-content-center align-self-center">
        <div class="col-4">
        <img class="img-fluid"
             src="/static/img/snake/explanation-3.png">
        </div>
        <p class="col-8 justify-content-center align-self-center">
          Avoid obstacles and collect food to score points!
        </p>
      </div>
    </div>
  </div>
</div>

<div id="playing" style="display: none">
  <style>
    #playing {
        width: 100vw;
        height: 100vh;
        position: fixed;
        top: 0;
        left: 0;
        z-index: 10000;
        background-color: lightgreen;
        text-align: center;
        padding: 1em;
        color: #555;
    }
    #score-span {
    }
    #score {
        color: black;
        font-weight: bold;
        font-size: 320%;
        margin-top: -0.3em;
    }
    #playing div {
        max-width: 600px;
        margin: auto;
    }
    #playing div.attention {
        padding: 0.8em;
    }
    #playing div.attention div {
        margin-top: 0.3em;
        margin-bottom: 0.3em;
    }
    #playing #color-name {
        color: white;
        background-color: black;
    }
  </style>

  <span id="score-span">
    score
    <div id="score">0</div>
  </span>

  <br>
  
  <div class="attention">
    <div>Swipe on this screen or use the arrow keys to move your snake</div>
    <div>Look at the window to see
      where to go </div>
    <div>Score points by getting the food (white spots)</div>
    <div>The color of your snake is <span id="color-name">unknown</span></div>
  </div>
  

  
</div>

<div id="game-over" style="display: none">
  <div class="text-center">
    <h1>Game over!</h1>

    <p>
      You scored <span id="final-score"></span>
    </p>
    <button onclick="window.location = window.location" class="btn btn-success fs-1">Play again</button>
  </div>


  <div id="high-scores">
    <table class="table" id="all-time">
      <thead>
        <tr>
          <th scope="col"></th>
          <th scope="col">Name</th>
          <th scope="col">Hallway</th>
          <th scope="col">Score</th>
        </tr>
      </thead>
      <tbody></tbody>
    </table>
  </div>
</div>


{% endblock %}