ilbright/urls.py
from django.urls import path

from . import views

app_name = 'ilbright'
urlpatterns = [
    path('', views.index, name='index'),
    path('send/', views.send, name='send'),
]

ilcam/urls.py
from django.urls import path

from . import views

app_name = 'ilcam'
urlpatterns = [
    path('', views.index, name='index'),
    path('send/', views.send, name='send'),
]

ildis/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'ildis'

urlpatterns = [
    path('', include('snake.urls')),
    path('suggestions/', include('suggestions.urls')),
    path('admin/', views.index_admin, name='index_admin'),
    path('admin/brightness/', include('ilbright.urls')),
    path('admin/text/', include('iltext.urls')),
    path('admin/camera/', include('ilcam.urls')),
    path('admin/specials/', include('specials.urls')),
    path('admin/admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

iltext/urls.py
from django.urls import path

from . import views

app_name = 'iltext'
urlpatterns = [
    path('', views.index, name='index'),
    path('send/', views.send, name='send'),

]

specials/urls.py
from django.urls import path

from . import views

app_name = 'specials'
urlpatterns = [
    path('', views.index, name='index'),
    path('send/', views.send, name='send'),
]

suggestions/urls.py
from django.urls import path

from . import views

app_name = 'suggestions'
urlpatterns = [
    path('', views.index, name='index'),
    path('send/', views.send, name='send'),

]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {# Load the tag library #}
  {% load bootstrap5 %}

  {# Load CSS and JavaScript #}
  {% bootstrap_css %}
  {% bootstrap_javascript %}

  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">


  <meta name="viewport" content="width=device-width, initial-scale=1">

  {% block head %}{% endblock %}

  <title>{% block title %}Leddie{% endblock %}</title>
</head>

<body>
  <div id="wrapper" class="container-sm">

    <nav class="navbar navbar-expand navbar-light bg-light sticky-top" aria-label="Second navbar example">
      <div class="container-fluid">
        <a class="navbar-brand" style="color: #dc3545; font-weight: bold;" href="/">Leddie</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample02" aria-controls="navbarsExample02" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExample02">
          <ul class="navbar-nav me-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'ilbright:index'%}">Brightness</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'iltext:index'%}">Text</a>
            </li>
          </ul>

          <a href="/accounts/logout" class="nav-link">Logout</a>
        </div>
      </div>
    </nav>


    <main id="content">
      {% block content %}{% endblock %}
    </main>
  </div>
</body>
</html>

templates/base_admin.html
<!DOCTYPE html>
<html lang="en">
<head>
  {# Load the tag library #}
  {% load bootstrap5 %}

  {# Load CSS and JavaScript #}
  {% bootstrap_css %}
  {% bootstrap_javascript %}

  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">


  <meta name="viewport" content="width=device-width, initial-scale=1">

  {% block head %}{% endblock %}

  <title>{% block title %}Leddie{% endblock %}</title>
</head>

<body>
  <div id="wrapper" class="container-sm">

    <nav class="navbar navbar-expand navbar-light bg-light sticky-top">
      <div class="container-fluid">
        <a class="navbar-brand" style="color: #dc3545; font-weight: bold;"
           href="{% url 'index_admin' %}">Leddie</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample02" aria-controls="navbarsExample02" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExample02">
          <ul class="navbar-nav me-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'suggestions:index'%}">Pub</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'ilbright:index'%}">Brght</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'iltext:index'%}">Txt</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'specials:index'%}">Spec</a>
            </li>
          </ul>

          <a href="/accounts/logout" class="nav-link">Logout</a>
        </div>
      </div>
    </nav>


    <main id="content">
      {% block content %}{% endblock %}
    </main>
  </div>
</body>
</html>

templates/base_public.html
<!DOCTYPE html>
<html lang="en">
<head>
  {# Load the tag library #}
  {% load bootstrap5 %}

  {# Load CSS and JavaScript #}
  {% bootstrap_css %}
  {% bootstrap_javascript %}

  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">


  <meta name="viewport" content="width=device-width, initial-scale=1">

  {% block head %}{% endblock %}

  <title>{% block title %}Leddie{% endblock %}</title>
</head>

<body>
  <div id="wrapper" class="container-sm">

    <nav class="navbar navbar-expand navbar-light bg-white
                border-bottom
                sticky-top">
      <div class="container-fluid">
        {% block nav %}
        <a class="navbar-brand" style="color: #dc3545; font-weight: bold;" href="/">Leddie</a>

        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'index_admin'%}">Admin</a>
          </li>
        </ul>
        {% endblock %}
      </div>
    </nav>


    <main id="content">
      {% block content %}{% endblock %}
    </main>

    <footer class="footer mb-3 py-3 border-top text-muted"
            style="font-size: 80%; margin-top: 4em;">
      <div class="row justify-content-between">
        <div class="col-6">
          This website is <a class="text-reset"
          href="https://github.com/jchmrt/ildis">free and open source
          software!</a>
        </div>
        <div class="col-6 text-end">
          Questions or suggestions: <a class="text-reset"
          href="mailto:leddie@invulns.nl">leddie@invulns.nl</a>
        </div>
      </div>
    </footer>
  </div>
</body>
</html>