ilbright/urls.py
from django.urls import path

from . import views

app_name = 'ilbright'
urlpatterns = [
    path('', views.index, name='index'),
    path('send/', views.send, name='send'),
]

ilcam/urls.py
from django.urls import path

from . import views

app_name = 'ilcam'
urlpatterns = [
    path('', views.index, name='index'),
    path('send/', views.send, name='send'),
]

ildis/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'ildis'

urlpatterns = [
    path('', include('snake.urls')),
    path('suggestions/', include('suggestions.urls')),
    path('admin/', views.index_admin, name='index_admin'),
    path('admin/brightness/', include('ilbright.urls')),
    path('admin/text/', include('iltext.urls')),
    path('admin/camera/', include('ilcam.urls')),
    path('admin/specials/', include('specials.urls')),
    path('admin/admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

iltext/urls.py
from django.urls import path

from . import views

app_name = 'iltext'
urlpatterns = [
    path('', views.index, name='index'),
    path('send/', views.send, name='send'),

]

specials/urls.py
from django.urls import path

from . import views

app_name = 'specials'
urlpatterns = [
    path('', views.index, name='index'),
    path('send/', views.send, name='send'),
]

ildis/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

def index(request):
    return render(request, 'index.html', {})

@login_required
def index_admin(request):
    return render(request, 'index_admin.html', {})

ildis/templates/index.html
{% extends "base_public.html" %}


{% block content %}

<div class="alert alert-warning" role="alert">
    <h4 class="alert-heading">Under construction</h4>
    <hr>
    <p>
      This page is under construction. In a few days, you will be able
      to suggest messages to show on the window here.
    </p>
</div>

<div class="card mb-3">
  <div class="card-header">
    <b>Admin</b>
  </div>
  <div class="card-body">
    <a href="{% url 'index_admin' %}">
      If you have a leddie.nl account, you can go to the admin site.
    </a>
  </div>
</div>


{% endblock %}

ildis/templates/index_admin.html
{% extends "base_admin.html" %}


{% block content %}

<div class="container g-3">
  <div class="card mb-3">
    <div class="card-header bg-danger text-white">
      <b>LEDs</b>
    </div>

    <ul class="list-group list-group-flush">
      <a class="list-group-item" href="{% url 'ilbright:index' %}">Brightness</a>
      <a class="list-group-item" href="{% url 'iltext:index' %}">Text</a>
      <a class="list-group-item" href="{% url 'specials:index' %}">Specials</a>
      <a class="list-group-item" href="{% url 'ilcam:index' %}">Camera</a>
    </ul>
  </div>

  <div class="card mb-3">
    <div class="card-header bg-warning">
      <b>Administration</b>
    </div>

    <ul class="list-group list-group-flush">
      <a class="list-group-item" href="{% url 'admin:index' %}">Admin</a>
    </ul>
  </div>
</div>

{% endblock %}